### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by KemoHena** [AngryCarrot789/FramePFX#9]
**Describe the bug**
![errorm](https://github.com/user-attachments/assets/f639d25b-b2f8-4f36-b701-fa86349ab874)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AngryCarrot789** [comment]
Did you put the FFmpeg dlls in the right folder?

**Comment by AngryCarrot789** [comment]
I updated the project to use the latest version of FFmpeg, turns out it was still using a really old version. Hopefully it should work now

**Comment by KemoHena** [comment]
I download new ffmpeg from
https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2024-12-11-13-02/ffmpeg-N-118048-g1e76bd2f39-win64-gpl.zip
and updated project, and the problem not fixed
![errorm4](https://github.com/user-attachments/assets/72e5fdad-698c-4a26-b67a-8cf19ef09ab2)

**Comment by AngryCarrot789** [comment]
The folder needs the DLLs too, the EXEs i'm pretty sure aren't required

**Comment by KemoHena** [comment]
This folder contain all files in your download link:
https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2024-12-11-13-02/ffmpeg-N-118048-g1e76bd2f39-win64-gpl.zip
No dll files in bin folder in this link

**Comment by AngryCarrot789** [comment]
I got the wrong link oops, I updated it now. If you redownload the project again, and download the updated link, you just have to copy the DLLs from the bin folder from the archive you downloaded, and copy into the FramePFX\libraries\ffmpeg folder and it should work

**Comment by KemoHena** [comment]
> I got the wrong link oops, I updated it now. If you redownload the project again, and download the updated link, you just have to copy the DLLs from the bin folder from the archive you downloaded, and copy into the FramePFX\libraries\ffmpeg folder and it should work

sorry nothing new, problem stll here
![errorm5](https://github.com/user-attachments/assets/af5e00b4-da7a-4ee2-ab17-76f032e38d59)

**Comment by AngryCarrot789** [comment]
Copy the DLLs into the ffmpeg folder instead of bin, that should do the trick

**Comment by KemoHena** [comment]
![errorm6](https://github.com/user-attachments/assets/5c9a1622-1bb7-4ad8-9800-bb554052d38b)

'FramePFX-DesktopUI.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Private.CoreLib.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\FramePFX-DesktopUI.dll'. Symbols loaded.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Runtime.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\hotreload\Microsoft.Extensions.DotNetDeltaApplier.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.IO.Pipes.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Linq.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Collections.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Console.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Threading.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Runtime.InteropServices.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Threading.Overlapped.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Security.AccessControl.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Security.Principal.Windows.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Security.Claims.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Runtime.Loader.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.Controls.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Collections.Concurrent.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.Base.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.ObjectModel.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.Desktop.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.Fonts.Inter.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.Win32.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\MicroCom.Runtime.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Numerics.Vectors.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.Skia.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.ComponentModel.Primitives.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Private.Uri.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\SkiaSharp.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.OpenGL.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\Microsoft.Win32.Primitives.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.ComponentModel.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Threading.Thread.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.Vulkan.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.MicroCom.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\netstandard.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.Metal.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Memory.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\FramePFX-core.dll'. Symbols loaded.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.Markup.Xaml.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.ComponentModel.TypeConverter.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.Themes.Simple.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.Controls.ColorPicker.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.Dialogs.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.Markup.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\HarfBuzzSharp.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\Avalonia.Diagnostics.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Users\hp\Downloads\FramePFX-master\FramePFX.Avalonia\bin\x64\Debug\net8.0\FFmpeg.AutoGen.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Collections.Specialized.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Xml.ReaderWriter.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Private.Xml.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Text.Encoding.Extensions.dll'. Symbol loading disabled by Include/Exclude setting.
Exception thrown: 'System.NotSupportedException' in FFmpeg.AutoGen.dll
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Diagnostics.StackTrace.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Reflection.Metadata.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Collections.Immutable.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.IO.MemoryMappedFiles.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Runtime.Intrinsics.dll'. Symbol loading disabled by Include/Exclude setting.
The thread '.NET TP Worker' (13688) has exited with code 0 (0x0).
The thread '.NET TP Worker' (13672) has exited with code 0 (0x0).
The thread '.NET TP Worker' (13684) has exited with code 0 (0x0).
The thread '.NET TP Worker' (13664) has exited with code 0 (0x0).
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Diagnostics.TraceSource.dll'. Symbol loading disabled by Include/Exclude setting.
[Binding]An error occurred binding 'ContentTemplate' to '$parent[Expander].HeaderTemplate' at '$parent[Expander]': 'Ancestor not found.' (ContentPresenter #PART_HeaderPresenter)
[Binding]An error occurred binding 'ContentTemplate' to '$parent[Expander].ContentTemplate' at '$parent[Expander]': 'Ancestor not found.' (ContentPresenter #PART_ContentPresenter)
[Binding]An error occurred binding 'ContentTemplate' to '$parent[Expander].HeaderTemplate' at '$parent[Expander]': 'Ancestor not found.' (ContentPresenter #PART_HeaderPresenter)
[Binding]An error occurred binding 'ContentTemplate' to '$parent[Expander].ContentTemplate' at '$parent[Expander]': 'Ancestor not found.' (ContentPresenter #PART_ContentPresenter)
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Linq.Expressions.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Reflection.Emit.ILGeneration.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Reflection.Emit.Lightweight.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Reflection.Primitives.dll'. Symbol loading disabled by Include/Exclude setting.
'FramePFX-DesktopUI.exe' (CoreCLR: clrhost): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
[Binding]An error occurred binding 'ContentTemplate' to '$parent[Expander].HeaderTemplate' at '$parent[Expander]': 'Ancestor not found.' (ContentPresenter #PART_HeaderPresenter)
[Binding]An error occurred binding 'ContentTemplate' to '$parent[Expander].ContentTemplate' at '$parent[Expander]': 'Ancestor not found.' (ContentPresenter #PART_ContentPresenter)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth0' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #3426769)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth1' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #30840926)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth2' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #9132882)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth0' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #27627990)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth1' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #23274750)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth2' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #8146160)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth0' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #17107576)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth1' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #43536440)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth2' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #56283646)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth0' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #66898301)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth1' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #50053294)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth2' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #47826462)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth0' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #7461047)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth1' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #365031)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth2' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #3285280)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth0' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #17227723)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth1' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #53268321)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth2' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #9652842)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth0' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #45461382)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth1' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #6499254)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth2' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #58493292)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth0' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #15165719)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth1' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #20463720)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth2' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #49955752)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth0' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #10789421)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth1' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #1527883)
[Binding]An error occurred binding 'Width' to '$templatedParent.PropertyEditor.ColumnWidth2' at 'PropertyEditor': 'Value is null.' (ColumnDefinition #13750947)
The program '[13368] FramePFX-DesktopUI.exe' has exited with code 0 (0x0).

**Comment by KemoHena** [comment]
Exception thrown: 'System.NotSupportedException' in FFmpeg.AutoGen.dll

**Comment by AngryCarrot789** [comment]
I don't know what's causing the problem...

I got it working by downloading the repo, then in FramePFX-master creating a folder "libraries" and then a subfolder to that "ffmpeg" and copying the files from FFmpeg's bin folder into that new ffmpeg folder, so the file `FramePFX-master\libraries\ffmpeg\avcodec-61.dll` should exist, along with 7 other dlls.

You are building in x64 right? AnyCPU/x86 won't work since the ffmpeg DLLs are x64

**Comment by KemoHena** [comment]
Yes in x64

**Comment by AngryCarrot789** [comment]
Hmm, could you try copying the 8 DLLs into the same directly as the build exe? Maybe the xcopy command isn't working properly.

**Comment by KemoHena** [comment]
I think it worked now, after rename folder name from FramePFX-master to FramePFX

**Comment by AngryCarrot789** [comment]
Interesting... glad you got it working 👍 I'll definitely work on trying to auto-download the right files or at least some sort of setup dialog at some point, i only just realised xcopy probably only works on windows yet the project should work on all platforms, and it's needed to copy the DLLs around

**Comment by KemoHena** [comment]
Thank you for the support

**Comment by AngryCarrot789** [comment]
The newer version is much simpler to download now. And FFmpeg is optional :D
